### ISSUE TITLE
Android 4.x.x

### ISSUE THREAD

**Issue by hrabkin** [yurifariasg/android-google-speech-sample#1]
Hi, thank you for sample it works awesome for Android 5+.

I need to support android 4.x.x and currently I'm investigating an issue with SSL error:

```
me.yurifariasg.speech_sample W/StreamingRecognizeClient: recognize failed: {0}: Status{code=UNAVAILABLE, description=No provided cause, cause=javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x50d5f6d0: Failure in SSL library, usually a protocol error
                                                                                        error:140740B5:SSL routines:SSL23_CLIENT_HELLO:no ciphers available (external/openssl/ssl/s23_clnt.c:486 0x41f58448:0x00000000)}
me.yurifariasg.speech_sample D/jdwp: sendRequest : Len=0x4D
me.yurifariasg.speech_sample D/dalvikvm: threadid=19: interp stack at 0x520a4000
me.yurifariasg.speech_sample D/dalvikvm: threadid=19: created from interp
me.yurifariasg.speech_sample D/dalvikvm: start new thread
me.yurifariasg.speech_sample D/dalvikvm: threadid=19: notify debugger
me.yurifariasg.speech_sample D/jdwp: sendRequest : Len=0x1D
me.yurifariasg.speech_sample D/dalvikvm: threadid=19 (grpc-timer-0): calling run()
me.yurifariasg.speech_sample E/StreamingRecognizeClient: Error to Recognize.
        io.grpc.StatusRuntimeException: UNAVAILABLE: No provided cause
            at io.grpc.Status.asRuntimeException(Status.java:545)
            at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:370)
            at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:458)
            at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$500(ClientCallImpl.java:385)
            at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$3.runInContext(ClientCallImpl.java:486)
            at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
            at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
            at java.lang.Thread.run(Thread.java:838)
         Caused by: javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x50d5f6d0: Failure in SSL library, usually a protocol error
        error:140740B5:SSL routines:SSL23_CLIENT_HELLO:no ciphers available (external/openssl/ssl/s23_clnt.c:486 0x41f58448:0x00000000)
            at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:413)
            at io.grpc.okhttp.OkHttpProtocolNegotiator.negotiate(OkHttpProtocolNegotiator.java:106)
            at io.grpc.okhttp.OkHttpProtocolNegotiator$AndroidNegotiator.negotiate(OkHttpProtocolNegotiator.java:172)
            at io.grpc.okhttp.OkHttpTlsUpgrader.upgrade(OkHttpTlsUpgrader.java:74)
            at io.grpc.okhttp.OkHttpClientTransport$1.run(OkHttpClientTransport.java:375)
                ... 4 more
         Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x50d5f6d0: Failure in SSL library, usually a protocol error
        error:140740B5:SSL routines:SSL23_CLIENT_HELLO:no ciphers available (external/openssl/ssl/s23_clnt.c:486 0x41f58448:0x00000000)
            at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_do_handshake(Native Method)
            at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:372)
                ... 8 more
me.yurifariasg.speech_sample D/libc-netbsd: getaddrinfo: speech.googleapis.com get result from proxy >>
```

I've tried update [security provider](https://developer.android.com/training/articles/security-gms-provider.html), but it didn't helped 
Seems like you have very large experience in working with Google APIs, do you have any ideas how to resolve this problem ?

**Comment by hrabkin** [comment]
I've created pull request with fix on this issue

**Comment by yurifariasg** [comment]
Hi Zestu, Thanks for submitting a PR!

Will close this issue and merge your code.
